---
Orderer: &OrdererDefaults
  OrdererType: solo
  Addresses:
  - orderer:7050
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:

Application: &ApplicationDefaults
  Organizations:



Organizations:
- &OrdererOrg
  Name: OrdererOrg
  ID: OrdererMSP
  MSPDir: cli/peers/ordererOrganizations/orderer-org/msp
- &ProducerOrg
  Name: ProducerOrgMSP
  ID: ProducerOrgMSP
  MSPDir: cli/peers/peerOrganizations/producer-org/msp
  AnchorPeers:
  - Host: producer-peer
    Port: 7051
- &DealerOrg
  Name: DealerOrgMSP
  ID: DealerOrgMSP
  MSPDir: cli/peers/peerOrganizations/dealer-org/msp
  AnchorPeers:
  - Host: dealer-peer
    Port: 7051
- &ConsumerOrg
  Name: ConsumerOrgMSP
  ID: ConsumerOrgMSP
  MSPDir: cli/peers/peerOrganizations/consumer-org/msp
  AnchorPeers:
  - Host: consumer-peer
    Port: 7051
- &AccreditorOrg
    Name: AccreditorOrgMSP
    ID: AccreditorOrgMSP
    MSPDir: cli/peers/peerOrganizations/accreditor-org/msp
    AnchorPeers:
    - Host: accreditor-peer
      Port: 7051

Profiles:
  FourOrgsGenesis:
    Orderer:
      <<: *OrdererDefaults
      Organizations:
      - *OrdererOrg
    Consortiums:
      GemConsortium:
        Organizations:
        - *ProducerOrg
        - *DealerOrg
        - *ConsumerOrg
        - *AccreditorOrg
  FourOrgsChannel:
    Consortium: GemConsortium
    Application:
      <<: *ApplicationDefaults
      Organizations:
      - *ProducerOrg
      - *DealerOrg
      - *ConsumerOrg
      - *AccreditorOrg